Logging
hytech-racing/drivebrain_software pull request #19
Opened 2024-11-10 18:56 UTC by happyCupcake

2024-11-11 17:57 UTC, RCMast3r requested changes
looks good, except go ahead and remove all the commented out code, no need to keep it around and fix the nix derivation.

2024-11-11 17:57 UTC, RCMast3r commented on default.nix
> +    "-DCMAKE_PREFIX_PATH=${fmt}/lib/cmake;${spdlog}/lib/cmake"
you shouldnt need to do this, nix already adds these for you

2024-11-11 17:57 UTC, RCMast3r commented on drivebrain_app/main.cpp
> +    // std::cout << "Interrupt signal (" << signal << ") received. Cleaning up..." << std::endl;
go ahead and remove all the places you commented the logs out

2024-11-11 17:57 UTC, RCMast3r commented on drivebrain_app/main.cpp
> +        // std::cout << desc << "\n";
pls remove commented code

2024-11-11 17:57 UTC, RCMast3r commented on drivebrain_app/main.cpp
> +            // std::cout <<"started db service thread" <<std::endl;
commented code

2024-11-11 17:57 UTC, RCMast3r commented on drivebrain_app/main.cpp
> +                spdlog::error("Error in io_context: {}", e.what());
commented code

2024-11-11 17:57 UTC, RCMast3r commented on drivebrain_app/main.cpp
> +    spdlog::info("joined io context");
commented code

2024-11-11 17:57 UTC, RCMast3r commented on drivebrain_core_base/src/JsonFileHandler.cpp
commented code

2024-11-12 20:44 UTC, RCMast3r approved these changes

2024-11-12 20:46 UTC, SreeDan approved these changes

2024-11-12 23:38 UTC, merged