Enum can protobuf compatability + mcap/protobuf logging of ht can and ht proto versions
hytech-racing/drivebrain_software pull request #9
Opened 2024-10-14 06:58 UTC by KrishKittur

2024-10-14 20:42 UTC, RCMast3r requested changes

2024-10-14 20:42 UTC, RCMast3r commented on CMakeLists.txt
> +    protobuf::libprotobuf
this shouldnt be needed, it is already linked to by several other targets

2024-10-14 20:42 UTC, RCMast3r commented on drivebrain_core_impl/drivebrain_comms/include/CANComms.hpp
> +        // deqtype &_output_deque_ref;
pls remove commented code

2024-10-14 20:42 UTC, RCMast3r commented on drivebrain_app/main.cpp
> +#include "base_msgs.pb.h"
shouldnt be a need to include the base_msgs here

2024-10-14 20:42 UTC, RCMast3r commented on drivebrain_core_impl/drivebrain_comms/src/CANComms.cpp
> +    const google::protobuf::Descriptor *desc = google::protobuf::DescriptorPool::generated_pool()->FindMessageTypeByName("hytech." + name);
should add a nullptr check here as we have already seen that this can cause a seg fault

2024-10-14 20:42 UTC, RCMast3r commented on drivebrain_core_impl/drivebrain_comms/src/CANComms.cpp
> +        auto msg_to_populate = _get_pb_msg_by_name(_to_lowercase(msg->Name()));
also add a nullptr check here, this can return nullptr if no pb message found

2024-10-14 20:42 UTC, RCMast3r commented on drivebrain_core_impl/drivebrain_comms/src/CANComms.cpp
> +                    // std::cout << "\t" << sig.Name() << "=" << sig.RawToPhys(sig.Decode(frame.data)) << sig.Unit() << "\n";
pls remove commented code

2024-10-14 20:42 UTC, RCMast3r commented on drivebrain_core_impl/drivebrain_comms/src/CANComms.cpp
> +    std::cout << "got message type name of " << messageTypeName << std::endl;
this print should be removed

2024-10-14 20:42 UTC, RCMast3r commented on drivebrain_core_impl/drivebrain_comms/src/CANComms.cpp
>                  sig.Encode(val, frame.data);
pls remove the commented code

2024-10-15 17:17 UTC, RCMast3r approved these changes

2024-10-19 01:32 UTC, SreeDan approved these changes

2024-11-14 22:48 UTC, RCMast3r commented
aight, there seem to be issues with this that need to be fixed:

![image](https://github.com/user-attachments/assets/2c2918d0-67f8-4fbf-84f3-3321f26c7b8b)

2024-11-28 00:09 UTC, RCMast3r requested changes

2024-11-28 00:09 UTC, RCMast3r commented on drivebrain_core_impl/drivebrain_comms/src/CANComms.cpp
> +            } },
switch to spdlog

2024-12-13 01:28 UTC, RCMast3r approved these changes

2024-12-13 01:28 UTC, merged